Repository Pda4thMiniProject4th/shitdown-fe, pull requests merged in 2024-05, with the labels that each got.

#4 feat: files - react 초기 세팅
  front-end/.gitignore
  front-end/README.md
  front-end/package-lock.json
  front-end/package.json
  front-end/public/favicon.ico
  front-end/public/index.html
  front-end/public/logo192.png
  front-end/public/logo512.png
  front-end/public/manifest.json
  front-end/public/robots.txt
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/App.test.js
  front-end/src/index.css
  front-end/src/index.js
  front-end/src/logo.svg
  front-end/src/reportWebVitals.js
  front-end/src/setupTests.js
Labels: 💡 Feature, :runner: init

#5 refactor: fiiles - 파일 관리의 편리성을 위한 폴더 위치 변경
  .gitignore
  front-end/.gitignore
  front-end/README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: :recycle: refactor, :runner: init

#6 chore: react CICD 추가
  .github/workflows/cicd.yml
Labels: 💡 Feature, :runner: init

#7 docs: README.md - 이름 수정
  README.md
Labels: :memo: docs

#9 Feat/folder seperate 폴더 생성
  src/admin/test.js
  src/shit/test.js
Labels: :briefcase: rename

#11 feat: files - seat 컴포넌트 테스트 코드
  src/test/components/seats/Row.js
  src/test/components/seats/Seat.js
  src/test/components/seats/SeatingChart.js
Labels: 💡 Feature

#13 SeatingChart.js 좌석 재배치
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/index.js
  src/test/components/seats/Seat.js
  src/test/components/seats/SeatingChart.js
Labels: 💡 Feature

#18 feat: files - 마이페이지 Drawer 기능
  package-lock.json
  package.json
  src/App.js
  src/test/components/myPage/Drawertest.js
Labels: 💡 Feature

#19 feat: 현재좌석 매핑 완료
  package.json
  src/test/components/seats/Row.js
  src/test/components/seats/Seat.js
  src/test/components/seats/SeatingChart_current.js
Labels: 💡 Feature

#22 feat: 메인페이지 공지 생성 완료, design: 메인페이지 구성 (마이페이지, 공지) 배치 완료
  src/App.css
  src/App.js
  src/test/components/mainPage/Mainpage.js
  src/test/components/notices/Notice.css
  src/test/components/notices/Notice.js
Labels: 💡 Feature

#24 feat: 자리 Select UI, 확인 Button UI, 메인페이지 화면 재구성
  src/test/components/mainPage/Mainpage.js
  src/test/components/seats/Root.js
  src/test/components/seats/Root2.js
  src/test/components/seats/Select.js
  src/test/components/seats/SelectButton.js
Labels: 💡 Feature

#26 feat: 마이페이지 API 연동 완료, fix: db 변경 후 데이터 조회 버그 수정
  src/test/components/myPage/Drawertest.js
Labels: 💡 Feature, :hammer_and_wrench: fix

#30 feat: (SelectButton.js,Root2.js) - 자리 선택 및 확정 API 연동 테스트 코드
  src/test/components/seats/Root2.js
  src/test/components/seats/SelectButton.js
Labels: 💡 Feature

#33 feat: selectbutton(실시간 좌석 선택)api 연결 및 모달창 생성
  src/test/components/seats/SeatingChart_current.js
  src/test/components/seats/SelectButton.js
Labels: 💡 Feature

#37 feat: SeatingChart_live.js - 실시간 자리 x 띄우기 완료
  src/test/components/seats/SeatingChart_live.js
Labels: 💡 Feature

#36 fix: seats/live api 수정 후 재연결(seat-option: 2추가)
  src/test/components/seats/SelectButton.js
Labels: :hammer_and_wrench: fix

#32 Feat: kakaologin 기능
  .gitignore
  package-lock.json
  package.json
  public/kakaologinbtn.png
  public/shitdownlogo.jpg
  src/App.js
  src/index.js
  src/login/components/Login.js
  src/login/components/LoginPage.js
  src/login/components/Redirect.js
  src/order/oderPage.js
Labels: 💡 Feature

#39 fix: seats/current api 수정 후 현재 죄석 배치 연결
  src/test/components/seats/SeatingChart_current.js
Labels: :hammer_and_wrench: fix

#41 refactor: files - 메인페이지 컴포넌트 재구성
  src/App.js
  src/test/components/mainPage/Mainpage.js
  src/test/components/seats/Root3.js
Labels: :recycle: refactor

#42 feat: hover 적용 시도
  src/test/components/seats/Row.js
  src/test/components/seats/Seat.css
  src/test/components/seats/Seat.js
  src/test/components/seats/SeatingChart_current.js
Labels: 💡 Feature

#44 feat: files - 자리 선택->버튼 클릭 후 좌석 x버튼 구현, 자리 선택 및 확정 API 연동 완료
  src/test/components/seats/Root3.js
  src/test/components/seats/SeatingChart_live.js
  src/test/components/seats/SelectButton.js
Labels: 💡 Feature

#45 design: 공지, 마이페이지 css 수정 및 추가
  src/test/components/myPage/Drawertest.js
  src/test/components/myPage/Mypage.css
  src/test/components/notices/Notice.css
Labels: :rose: style

#47 feat: hover 기능 적용
  src/test/components/seats/Row.js
  src/test/components/seats/SeatingChart_current.js
Labels: 💡 Feature

#49 refactor: 실시간 좌석 코드 리팩토링
  src/test/components/seats/Row2.js
  src/test/components/seats/Seat2.js
  src/test/components/seats/SeatingChart_live.js
Labels: :recycle: refactor

#50 design: files - Root3 컴포넌트 재구성 및 css 테스트
  src/test/components/myPage/Drawertest.js
  src/test/components/seats/Root3.css
  src/test/components/seats/Root3.js
  src/test/components/seats/SelectButton.js
Labels: :rose: style

#52 feat: 자리 배치 페이지 시작 시 화면 리랜더링 되게 구현
  src/admin/seatArrange/components/AdminSeatArrange.js
  src/admin/seatArrange/components/AdminSeatingChart.js
Labels: 💡 Feature, :hammer_and_wrench: fix

#54 refactor: 메인페이지(마이페이지, 공지, 현재좌석, 실시간좌석) props 적용
  src/test/components/mainPage/Mainpage.js
  src/test/components/myPage/Drawertest.js
  src/test/components/notices/Notice.js
  src/test/components/seats/Root3.js
  src/test/components/seats/Row.js
  src/test/components/seats/Seat.js
  src/test/components/seats/SeatingChart_current.js
  src/test/components/seats/SeatingChart_live.js
  src/test/components/seats/SelectButton.js
Labels: :recycle: refactor

#55 refactor: seatCurrent관련된 파일들 주석 정리 및 변수 조정
  src/test/components/myPage/Drawertest.js
  src/test/components/seats/Row.js
  src/test/components/seats/Seat.js
  src/test/components/seats/SeatingChart_current.js
Labels: :recycle: refactor

#56 Feat: 이름과 기수를 받아오기
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/login/components/Login.js
  src/login/components/Redirect.js
  src/order/oderPage.js
Labels: 💡 Feature

#57 design: 메인페이지, 공지, 실시간좌석 자리 디자인 수정
  src/test/components/mainPage/Mainpage.css
  src/test/components/mainPage/Mainpage.js
  src/test/components/notices/Notice.css
  src/test/components/seats/Root3.css
  src/test/components/seats/Root3.js
  src/test/components/seats/Seat2.js
  src/test/components/seats/SeatingChart_live.js
Labels: :rose: style

#58 design: files - navbar를 위한 마이페이지, 공지 분리 css
  src/test/components/mainPage/Mainpage.js
  src/test/components/notices/Notice.css
Labels: :rose: style

#60 feat: 전역 폰트 적용
  src/App.js
  src/fonts/MangoDdobak-B(ttf).ttf
  src/index.css
  src/test/components/myPage/Drawertest.js
  src/test/components/myPage/icon.svg
  src/test/components/myPage/nav.css
Labels: 💡 Feature

#61 design: 메인페이지, 실시간좌석, 현재좌석 css 수정
  src/test/components/seats/Root3.css
  src/test/components/seats/Root3.js
  src/test/components/seats/Seat2.js
  src/test/components/seats/SeatingChart_current.js
Labels: :rose: style

#62 style: 버튼과 입력창 가운데로 정렬
  src/order/oderPage.js
  src/test/components/seats/SeatingChart_current.js
Labels: :rose: style

#63 design: 메인페이지 공지 아이콘 추가
  src/test/components/notices/Notice.css
  src/test/components/notices/Notice.js
Labels: :rose: style

#64 design: 좌석 재배치
  src/test/components/seats/Row.js
  src/test/components/seats/Row2.js
Labels: :rose: style

#65 feat: 중간 merge
  package-lock.json
  package.json
  src/App.js
  src/login/components/LoginPage.js
  src/order/oderPage.js
  src/test/components/mainPage/Mainpage.js
Labels: 💡 Feature

#66 feat: 유저 admin 여부 받기
  src/order/oderPage.js
Labels: 💡 Feature

#67 feat: 메인페이지 수정
  src/test/components/mainPage/Mainpage.js
  src/test/components/myPage/Drawertest.js
  src/test/components/notices/Notice.js
  src/test/components/seats/Root3.css
  src/test/components/seats/Root3.js
  src/test/components/seats/Seat.css
  src/test/components/seats/Seat.js
  src/test/components/seats/Seat2.css
  src/test/components/seats/Seat2.js
  src/test/components/seats/SeatingChart_current.js
  src/test/components/seats/SeatingChart_live.js
Labels: 💡 Feature

#71 feat: CICD S3BUCKET
  .github/workflows/cicd.yml
Labels: 💡 Feature

#70 feat: 토큰의 유효에 따른 페이지 이동
  src/login/components/Login.js
  src/order/oderPage.js
Labels: 💡 Feature

#72 fix: cicd.yml - 에러 수정
  .github/workflows/cicd.yml
Labels: :hammer_and_wrench: fix

#73 fix: cicd.yml - 진짜 마지막 에러 수정
  .github/workflows/cicd.yml
Labels: :hammer_and_wrench: fix

#74 fix: cicd.yml - 진짜진짜 마지막
  .github/workflows/cicd.yml
Labels: :hammer_and_wrench: fix

#75 refactor: 기수 정보 API 연동 완료
  src/test/components/mainPage/Mainpage.js
  src/test/components/notices/Notice.js
  src/test/components/seats/SeatingChart_current.js
  src/test/components/seats/SeatingChart_live.js
  src/test/components/seats/SelectButton.js
Labels: :recycle: refactor

#77 실시간 title 위치조정
  src/test/components/seats/Root3.css
Labels: 💡 Feature

#79 design: navbar css 변경
  src/test/components/myPage/Drawertest.js
  src/test/components/myPage/nav.css
  src/test/components/seats/Seat.js
Labels: :rose: style

#81 Feat/manageuserpage
  package.json
  src/admin/seatArrange/components/AdminNavbar.js
  src/admin/seatArrange/components/AdminPage.js
  src/admin/seatArrange/components/ManageUser.js
  src/admin/seatArrange/components/Reason.js
  src/admin/seatArrange/components/UserInfo.js
  src/admin/seatArrange/css/UserInfo.css
  src/login/components/LoginPage.js
  src/order/oderPage.js
Labels: 💡 Feature, :recycle: refactor

#82 design: 마이페이지 위치, 메인페이지 navbar css 수정, 현재좌석/실시간좌석 screen 추가, selectButton text 변경
  src/test/components/myPage/Drawertest.js
  src/test/components/myPage/nav.css
  src/test/components/seats/Root3.css
  src/test/components/seats/Screen.js
  src/test/components/seats/Screen2.js
  src/test/components/seats/SeatingChart_current.js
  src/test/components/seats/SeatingChart_live.js
  src/test/components/seats/SelectButton.js
Labels: :rose: style

#83 style: 정보 입력 페이지 UI 변경
  package-lock.json
  src/login/components/Login.js
  src/order/oderPage.js
  src/test/components/myPage/Drawertest.js
Labels: :rose: style

#84 refactor: 관지라 페이지 css 변경
  package-lock.json
  src/admin/seatArrange/components/AdminSeatArrange.js
  src/admin/seatArrange/components/AdminSeatingChart.js
  src/admin/seatArrange/components/Row.js
  src/admin/seatArrange/components/Seat.js
  src/admin/seatArrange/css/AdminNavbar.css
  src/admin/seatArrange/css/AdminNotice.css
  src/admin/seatArrange/css/UserInfo.css
Labels: 💡 Feature, :recycle: refactor

#85 design: files - 최종 메인페이지(마이페이지, 공지, 현재 좌석, 실시간 좌석) 디자인 완료
  src/App.js
  src/index.css
  src/index.js
  src/test/components/myPage/Drawertest.js
  src/test/components/myPage/Mypage.css
  src/test/components/seats/Root3.css
  src/test/components/seats/Screen.js
  src/test/components/seats/Seat.css
  src/test/components/seats/Seat.js
  src/test/components/seats/Seat2.css
  src/test/components/seats/Seat2.js
  src/test/components/seats/SelectButton.js
Labels: :rose: style

#87 style: 로그아웃 버튼 디자인 변경
  src/test/components/myPage/Drawertest.js
Labels: :rose: style

#89 feat: slack과 연동
  package.json
  public/favicon.ico
  public/index.html
  src/admin/CaptureImg.js
  src/admin/seatArrange/components/AdminNotice.js
  src/admin/seatArrange/components/AdminSeatArrange.js
  src/admin/seatArrange/components/Reason.js
  src/admin/seatArrange/components/Seat.js
  src/admin/seatArrange/components/SeatArrange.js
  src/admin/seatArrange/components/UserInfo.js
  src/admin/sendMessage.js
  src/order/oderPage.js
Labels: 💡 Feature

#90 feat: 관리자 페이지 - 유저 관리 페이지 개발
  src/admin/seatArrange/components/Reason.js
  src/admin/seatArrange/components/UserInfo.js
Labels: 💡 Feature

#91 feature: 현재 좌석 본인 자리 컬러링
  src/test/components/seats/Seat.js
Labels: 💡 Feature

#92 fix: Reasion.js - 기수 변경 시 seat_option이 변경 안되는 현상 수정
  src/admin/seatArrange/components/Reason.js
Labels: :hammer_and_wrench: fix
